provider:
  name: openfaas
  gateway: https://faas.srv.disarm.io
functions:
  fn-bvbd:
    lang: python-geospatial
    handler: ./function
    image: disarm/fn-bvbd:0.2.0
    environment:
      exec_timeout: 1020
      write_timeout: 1000
      read_timeout: 1000
      combine_output: false
      # write_debug: true
    labels:
      com.openfaas.scale.zero: true
